# You can create the issue in a different repo than where the problem is. Just make sure you have installed the bot on the configured repository.
# The issue will link back to the original repository where the contribution will be made.
repository: p5.js

# you can change the labels to suit your needs if "first-timers-only" is not what you are looking for.
# These are some examples.
labels:
  - first-timers-only
  - help wanted
  - good first issue
  - hacktoberfest

# If you would like to add your own template for the issue, add an .md file to your .github folder
# template: .github/first-timers-issue-template.md 
