"area:Accessibility":
  - '\[X\] Accessibility \(Web Accessibility\)'
"Build Process":
  - '\[X\] Build tools and processes'
"area:Color":
  - '\[X\] Color'
"area:Core":
  - '\[X\] Core'
"area:Data":
  - '\[X\] Data'
"area:DOM":
  - '\[X\] DOM'
"area:Events":
  - '\[X\] Events'
"Friendly-Errors":
  - '\[X\] Friendly error system'
"area:Image":
  - '\[X\] Image'
"area:IO":
  - '\[X\] IO \(Input/Output\)'
"Localization":
  - '\[X\] Localization'
"area:Math":
  - '\[X\] Math'
"Unit Testing":
  - '\[X\] Unit Testing'
"area:Typography":
  - '\[X\] Typography'
"area:Utilities":
  - '\[X\] Utilities'
"area:WebGL":
  - '\[X\] WebGL'
