name: 💡 Existing Feature Enhancement
description: This template is for suggesting an improvement for an existing feature.
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Increasing Access
      description: How would this new feature help [increase access](https://github.com/processing/p5.js/blob/main/contributor_docs/access.md) to p5.js? (If you're not sure, you can type "Unsure" here and let others from the community offer their thoughts.)
    validations:
      required: true
  - type: checkboxes
    id: sub-area
    attributes:
      label: Most appropriate sub-area of p5.js?
      description: You may select more than one.
      options:
        - label: Accessibility (Web Accessibility)
        - label: Color
        - label: Core/Environment/Rendering
        - label: Data
        - label: DOM
        - label: Events
        - label: Image
        - label: IO (Input/Output)
        - label: Math
        - label: Typography
        - label: Utilities
        - label: WebGL
        - label: Build tools and processes
        - label: Unit Testing
        - label: Friendly error system
        - label: Localization
        - label: Other (specify if possible)
  - type: textarea
    attributes:
      label: Feature enhancement details
    validations:
      required: true
