name: Found a Bug
description: This template is for reporting bugs (broken or incorrect behaviour). If you have questions about your own code, please visit our forum discourse.processing.org instead.
title: ""
labels: [bug]
body:
- type: checkboxes
  id: sub-area
  attributes:
    label: Most appropriate sub-area of p5.js?
    description: You may select more than one.
    options:
      - label: Accessibility (Web Accessibility)
      - label: Build tools and processes
      - label: Color
      - label: Core/Environment/Rendering
      - label: Data
      - label: DOM
      - label: Events
      - label: Friendly error system
      - label: Image
      - label: IO (Input/Output)
      - label: Localization
      - label: Math
      - label: Unit Testing
      - label: Typography
      - label: Utilities
      - label: WebGL
      - label: Other (specify if possible)
- type: textarea
  attributes:
    label: p5.js version 
    description: You can find this in the first line of the p5.js file.
  validations:
    required: true
- type: textarea
  attributes:
    label: Web browser and version 
    description: In the address bar, on Chrome enter "chrome://version", on Firefox enter "about:support". On Safari, use "About Safari".
  validations:
    required: true
- type: textarea
  attributes:
    label: Operating System 
    description: "Ex: Windows/MacOSX/Linux/Android/iOS along with version"
  validations:
    required: true
- type: textarea
  attributes:
    label: Steps to reproduce this 
    description: Include a simple code snippet that demonstrates the problem, along with any console errors produced. If this isn't possible, then simply describe the issue as best you can!
  validations:
    required: true