name: Linting Code

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
        with:
          persist-credentials: false
      - name: Use Node.js 22.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22.x
      - name: Get node modules
        run: npm ci
        env:
          CI: true
      - name: Lint source code
        run: npm run lint
