name: Publish approved pull requests and latest commit to pkg.pr.new
on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'
    tags:
      - '!**'

permissions:
  pull-requests: write
  issues: write

jobs:
  publish:
    if: github.repository == 'processing/p5.js'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build library
        run: npm run build

      - name: Publish library
        run: npx pkg-pr-new publish --no-template --json output.json --comment=off

      - name: Include PR info in output file
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        with:
          script: |
            const fs = require('fs');
            const output = JSON.parse(fs.readFileSync('output.json', 'utf8'));
            output.workflow = {
              pull_request: process.env.PR_NUMBER ? {
                number: process.env.PR_NUMBER
              } : null
            };
            fs.writeFileSync('output.json', JSON.stringify(output));

      - name: Upload output data
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: output.zip
          path: output.json
